<a href="https://colab.research.google.com/github/mariocuadra/Curso-Arduino-desde-cero/blob/master/Ejercicio_1_1_Introduccion_a_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
a=np.array([0,1,2,3,4,5])

# EN NumPy creamos los arrays como las listas de Python. Ademas, tiene la ventaja de que podemos trasnformar la dimension de los arrays tal como se expone en el ejemplo

b = a.reshape((3,2))
# Visualiza el contenido del array
b



array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
# para averiguar la dimensión
b.ndim

# Para averiguara las dimensiones del array
b.shape

# para modificar un valor del array:

b[1][0]=77

# Comprueba que lo has modificado
b

# Y ademas, podemos comprobar que esta modificacion se ha realizado tambien en el array

a

array([ 0,  1, 77,  3,  4,  5])

In [ ]:
# caso de querer que el array sea copiado y se consideren como 2 arrays distintos, deberiamos de hacer la siguiente operación:

c= a.reshape((3,2)).copy()

# visualiza c
c

#Modifica c

c[0][0] = -99



array([[-99,   1],
       [ 77,   3],
       [  4,   5]])

In [ ]:
# con Numpy podemos propagar los cambios a todos los elementos

a*2

a




array([ 0,  1, 77,  3,  4,  5])

In [ ]:
a**2 # raiz cuadrada



array([   0,    1, 5929,    9,   16,   25])

In [ ]:
# En NumPy, las operaciones de adición y sustracción de una lista son un poco mas complejas, permite usar los valores de array como indices.

a[np.array([2,3,4])]

array([77,  3,  4])

In [ ]:
# Tambien puede haber comparaciones con los elementos

a>4

# tambien podria ser utilizado para la corrección de outliers al mayor que podemos tener.

a[a>4] = 4

# Hay funciones para marcar los rangos superior e inferior de los valores.

a.clip(0,4)

a

array([0, 1, 4, 3, 4, 4])

In [ ]:
#Podemos contener valores invalidos que son marcados como numpy.nan
c= np.array([1,2, np.NAN,3,4])

#Visualiza el array para ver el nan
c



array([ 1.,  2., nan,  3.,  4.])

In [ ]:
#incluso se puede preguntar si contiene algun valor invalido.
np.isnan(c)

array([False, False,  True, False, False])

In [ ]:
# Y mostrar todos los valores validos con la siguiente sentencia.
c[~np.isnan(c)]


array([1., 2., 3., 4.])

In [ ]:
# O sacar la media de los valores válidos
np.mean(c[~np.isnan(c)])

2.5

In [ ]:
#sacar la media de valores validos
# Scipy ofrece muchos algoritmos para trabajar en NumPy con análisis predictivo.
import scipy, numpy

scipy.version.full_version



'1.4.1'

In [ ]:
scipy.dot is numpy.dot

False